### ISSUE TITLE
publish the docker file

### ISSUE THREAD

**Issue by DoctusHartwald** [jponge/vertx-devoxxfr19-demos#3]
hello,
As mention in devoxx 2019 you are using a docker file (to have the different components mongo,kakfa etc)
* Can you please publish it in git ? 
do you have the oc command associate to deploy it in openshift?

thanks again for the deme 👍 
regards

**Comment by jponge** [comment]
It's here (`docker-compose up` from the project root): https://github.com/jponge/vertx-devoxxfr19-demos/blob/master/docker-compose.yml
